name: ci
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch: {} # support manual runs
permissions:
  contents: read
jobs:
  build-connect-library:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode version
        # https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md#xcode
        run: sudo xcode-select --switch /Applications/Xcode_14.1.app
      - name: Build Connect library
        run: swift build
  build-eliza-cocoapods-example:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode version
        # https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md#xcode
        run: sudo xcode-select --switch /Applications/Xcode_14.1.app
      - name: Build Eliza CocoaPods example
        run: |
          cd ConnectExamples/ElizaCocoaPodsApp
          pod install
          xcodebuild -workspace ElizaCocoaPodsApp.xcworkspace -scheme ElizaCocoaPodsApp build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
  build-eliza-swiftpm-example:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode version
        # https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md#xcode
        run: sudo xcode-select --switch /Applications/Xcode_14.1.app
      - name: Build Eliza Swift PM example
        run: |
          cd ConnectExamples/ElizaSwiftPackageApp
          xcodebuild -scheme ElizaSwiftPackageApp build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
  build-plugin-and-generate:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1.12.0
        with:
          github_token: ${{ github.token }}
      - name: Build Connect plugins
        run: make buildplugins
      - name: Generate outputs
        run: make generate
      - name: Ensure no generated diff
        run: |
          git update-index --refresh --add --remove
          git diff-index --quiet HEAD --
  run-connect-tests:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: docker-practice/actions-setup-docker@master
      - name: Select Xcode version
        # https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md#xcode
        run: sudo xcode-select --switch /Applications/Xcode_14.1.app
      - name: Run tests
        run: make test
  run-swiftlint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/realm/swiftlint:0.50.3
    steps:
      - uses: actions/checkout@v3
      - name: Run SwiftLint
        run: swiftlint lint --strict
  validate-license-headers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate license headers
        run: |
          make licenseheaders
          git update-index --refresh
          git diff-index --quiet HEAD --
