name: lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  swiftlint:
    name: swiftlint
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/realm/swiftlint:0.50.3
    steps:
      - uses: actions/checkout@v3
      - name: Run SwiftLint
        run: swiftlint lint --strict
