name: lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  buildifier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: bazelbuild/setup-bazelisk@v2
      - name: Run Buildifier
        run: make buildifier-check

  swiftlint:
    name: swiftlint
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/realm/swiftlint:0.50.3
    steps:
      - uses: actions/checkout@v3
      - name: Run SwiftLint
        run: swiftlint lint --strict
