name: release
on:
  push:
    tags:
      - "*"
  workflow_dispatch: {} # support manual runs
permissions:
  contents: write
jobs:
  release:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1.15.0
        with:
          github_token: ${{ github.token }}
      - name: Build plugins
        run: make buildplugins
      - name: Zip artifacts
        run: |
          mkdir -p ./.tmp/artifacts
          tar -zcvf ./.tmp/artifacts/protoc-gen-connect-swift.tar.gz ./.tmp/bin/protoc-gen-connect-swift
          tar -zcvf ./.tmp/artifacts/protoc-gen-connect-swift-mocks.tar.gz ./.tmp/bin/protoc-gen-connect-swift-mocks
      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          append_body: true
          files: |
            ./.tmp/artifacts/*
